-- DDL migration.
-- Этот файл создаёт схему PostgreSQL для приложения "Авиакасса".
-- DDL означает Data Definition Language: создание таблиц и ограничений.

CREATE TABLE IF NOT EXISTS flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(255) NOT NULL UNIQUE,
    destination VARCHAR(255) NOT NULL,
    departure_date DATE NOT NULL,
    capacity INTEGER NOT NULL
);

-- Таблица passengers хранит пассажиров: ФИО, паспорт и контакты.
CREATE TABLE IF NOT EXISTS passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    passport_data VARCHAR(255) NOT NULL,
    contacts VARCHAR(255)
);

-- Таблица bookings связывает рейс и пассажира.
-- Ограничение uk_booking_flight_seat запрещает два бронирования на одно место в одном рейсе.
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL REFERENCES flights(id),
    passenger_id BIGINT NOT NULL REFERENCES passengers(id),
    service_class VARCHAR(255) NOT NULL CHECK (service_class IN ('ECONOMY', 'BUSINESS', 'FIRST')),
    seat VARCHAR(255) NOT NULL,
    CONSTRAINT uk_booking_flight_seat UNIQUE (flight_id, seat)
);
